[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
geo = "0.27.0"
geo-types = "0.7.12"
itertools = "0.12.0"
ndarray = "0.15.6"
